<?php

function hello_user_login($account) {
  // Fonction t().
  // Il existe 3 types de jetons indiquant comment on substitue les variables.
  // ! : le contenu de la variable est interprété.
  // @ : le contenu de la variable est échappé.
  // % : le contenu de la variable est échappé et la balise <em> est ajoutée.
  drupal_set_message(t('Welcome dear %name!',
                       array('%name' => $account->getAccountName())
  ));
}

/**
 * Implements hook_node_update().
 * @param \Drupal\node\NodeInterface $node
 */
function hello_node_update(NodeInterface $node) {
  $user = \Drupal::currentUser();
  $database = \Drupal::database();

  $database->insert('hello_node_history')
    ->fields(array(
      'nid' => $node->id(),
      'uid' => $user->id(),
      'update_time' => time(),
    ))
    ->execute();
}

/**
 * Implements hook_theme().
 */
function hello_theme($existing, $type, $theme, $path) {
  return array(
    'hello_node_history' => array(
      'template'  => 'hello-node-history',  // Automatiquement appelé en fonction du nom du hook de thème.
      'variables' => array(
        'node'  => NULL,
        'count' => NULL,
      ),
    ),
  );
}